# Ejercicios manejo básico de pandas

Importamos la libreria pandas

In [1]:
import pandas as pd

Leemos un archivo .csv desde el directorio raíz

In [2]:
archivo=pd.read_csv('rpi_data_long.csv')
archivo

,Ping:,26.992,ms,Download:,91.8,Mbit/s,Upload:,14.31,Mbit/s.1,11/24/2016 13:36
0,Ping:,24.532,ms,Download:,88.19,Mbit/s,Upload:,14.12,Mbit/s,11/24/2016 13:36
1,Ping:,20.225,ms,Download:,59.86,Mbit/s,Upload:,14.11,Mbit/s,11/24/2016 13:37
2,Ping:,19.332,ms,Download:,91.81,Mbit/s,Upload:,14.22,Mbit/s,11/24/2016 13:37
3,Ping:,22.494,ms,Download:,92.05,Mbit/s,Upload:,14.08,Mbit/s,11/24/2016 13:38
4,Ping:,17.586,ms,Download:,91.88,Mbit/s,Upload:,14.18,Mbit/s,11/24/2016 13:39
...,...,...,...,...,...,...,...,...,...,...
674,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
676,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Creamos un arreglo para reemplazar los nombres de las columnas del archivo original

In [3]:
column_names = [ 'Tipo A', 'Medida A', 'Unidad A',
                 'Tipo B', 'Medida B', 'Unidad B',
                 'Tipo C', 'Medida C', 'Unidad C', 
                 'Fecha']

Reeemplazamos los nombres de las columnas

In [4]:
archivo.columns = column_names
archivo

,Tipo A,Medida A,Unidad A,Tipo B,Medida B,Unidad B,Tipo C,Medida C,Unidad C,Fecha
0,Ping:,24.532,ms,Download:,88.19,Mbit/s,Upload:,14.12,Mbit/s,11/24/2016 13:36
1,Ping:,20.225,ms,Download:,59.86,Mbit/s,Upload:,14.11,Mbit/s,11/24/2016 13:37
2,Ping:,19.332,ms,Download:,91.81,Mbit/s,Upload:,14.22,Mbit/s,11/24/2016 13:37
3,Ping:,22.494,ms,Download:,92.05,Mbit/s,Upload:,14.08,Mbit/s,11/24/2016 13:38
4,Ping:,17.586,ms,Download:,91.88,Mbit/s,Upload:,14.18,Mbit/s,11/24/2016 13:39
...,...,...,...,...,...,...,...,...,...,...
674,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
676,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Copiamos el archivo enun archivo auxiliar

In [5]:
auxiliar= archivo.copy()
auxiliar

,Tipo A,Medida A,Unidad A,Tipo B,Medida B,Unidad B,Tipo C,Medida C,Unidad C,Fecha
0,Ping:,24.532,ms,Download:,88.19,Mbit/s,Upload:,14.12,Mbit/s,11/24/2016 13:36
1,Ping:,20.225,ms,Download:,59.86,Mbit/s,Upload:,14.11,Mbit/s,11/24/2016 13:37
2,Ping:,19.332,ms,Download:,91.81,Mbit/s,Upload:,14.22,Mbit/s,11/24/2016 13:37
3,Ping:,22.494,ms,Download:,92.05,Mbit/s,Upload:,14.08,Mbit/s,11/24/2016 13:38
4,Ping:,17.586,ms,Download:,91.88,Mbit/s,Upload:,14.18,Mbit/s,11/24/2016 13:39
...,...,...,...,...,...,...,...,...,...,...
674,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
676,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Cambiamos el nombre de las columnas en relación con las medidas como se muestra:

    Medida A -> Ping (ms)
    Medida B -> Descargar (Mbit/s)
    Medida C -> Cargar (Mbit/s)

In [6]:
auxiliar.rename(columns={'Medida A':'Ping (ms)', 
                           'Medida B': 'Download (Mbit/s)',
                           'Medida C': 'Upload (Mbit/s)'}, inplace=True)
auxiliar.head(3)

,Tipo A,Ping (ms),Unidad A,Tipo B,Download (Mbit/s),Unidad B,Tipo C,Upload (Mbit/s),Unidad C,Fecha
0,Ping:,24.532,ms,Download:,88.19,Mbit/s,Upload:,14.12,Mbit/s,11/24/2016 13:36
1,Ping:,20.225,ms,Download:,59.86,Mbit/s,Upload:,14.11,Mbit/s,11/24/2016 13:37
2,Ping:,19.332,ms,Download:,91.81,Mbit/s,Upload:,14.22,Mbit/s,11/24/2016 13:37

Eliminaremos las columnas de los tipos

In [7]:
auxiliar.drop(['Tipo A', 'Tipo B', 'Tipo C'], axis=1, inplace=True)
auxiliar.head()

,Ping (ms),Unidad A,Download (Mbit/s),Unidad B,Upload (Mbit/s),Unidad C,Fecha
0,24.532,ms,88.19,Mbit/s,14.12,Mbit/s,11/24/2016 13:36
1,20.225,ms,59.86,Mbit/s,14.11,Mbit/s,11/24/2016 13:37
2,19.332,ms,91.81,Mbit/s,14.22,Mbit/s,11/24/2016 13:37
3,22.494,ms,92.05,Mbit/s,14.08,Mbit/s,11/24/2016 13:38
4,17.586,ms,91.88,Mbit/s,14.18,Mbit/s,11/24/2016 13:39

Elimine las columnas de las Unidades

In [8]:
# Code cell 28
auxiliar['Día'] = auxiliar['Fecha'].apply(lambda x: pd.to_datetime(x).date())

In [9]:
auxiliar

,Ping (ms),Unidad A,Download (Mbit/s),Unidad B,Upload (Mbit/s),Unidad C,Fecha,Día
0,24.532,ms,88.19,Mbit/s,14.12,Mbit/s,11/24/2016 13:36,2016-11-24
1,20.225,ms,59.86,Mbit/s,14.11,Mbit/s,11/24/2016 13:37,2016-11-24
2,19.332,ms,91.81,Mbit/s,14.22,Mbit/s,11/24/2016 13:37,2016-11-24
3,22.494,ms,92.05,Mbit/s,14.08,Mbit/s,11/24/2016 13:38,2016-11-24
4,17.586,ms,91.88,Mbit/s,14.18,Mbit/s,11/24/2016 13:39,2016-11-24
...,...,...,...,...,...,...,...,...
674,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
676,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
677,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT

Cree una columna con la hora y elimine la columna fecha

Guarde el data frame con el nombre prueba.csv

In [10]:
auxiliar.max()

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_980\3801711907.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  auxiliar.max()

Ping (ms)            76.528
Download (Mbit/s)    92.870
Upload (Mbit/s)      14.550
dtype: float64

In [11]:
auxiliar.mad()

Ping (ms)            2.243702
Download (Mbit/s)    1.912033
Upload (Mbit/s)      0.569745
dtype: float64

In [12]:
auxiliar.min()

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_980\3516740667.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  auxiliar.min()

Ping (ms)            16.167
Download (Mbit/s)    58.480
Upload (Mbit/s)       6.210
dtype: float64